on: [push]

name: build

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly 2021-05-21
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2021-05-21
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Format Check
        run: cargo fmt --all -- --check
      - name: Clippy Test
        run: cargo clippy --profile test -- -D warnings -D clippy::dbg_macro